### ISSUE TITLE
Links to datasets are broken

### ISSUE THREAD

**Issue by yuyu2172** [tinghuiz/flowweb#1]
Hello.
Links to the datasets used in the paper are broken.
Could you please fix them?

**Comment by tinghuiz** [comment]
Hm, seems fine to me. Can you try a different browser? If you are using chrome, it might block downloading tar.gz files by default.

**Comment by yuyu2172** [comment]
The urls were fine. It worked when I tried downloading data using wget.

FYI, I was using Chrome when I could not download.

Thanks for replying quickly.
